branches:
  only:
    - master
    - develop
    - next
language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=6 DBUS_SESSION_BUS_ADDRESS=/dev/null
cache:
  directories:
    - node_modules
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm install -g npm@latest
  - npm --version
  - npm install
script:
  - npm test
  - cat test/unit/coverage/lcov.info | node_modules/.bin/coveralls
