#
# Theme settings
#
googleAnalytics: UA-98870917-1
# Package description
pkg:
  name: vuelayers
  fullname: VueLayers.js
  version: 0.6.2
  repo: https://github.com/ghettovoice/vuelayers
  download: https://github.com/ghettovoice/vuelayers/archive/master.zip
  author:
    name: Vladimir Vershinin
    user: ghettovoice
    homepage:
      url: https://ghettovoice.github.io
      name: Vladimir Vershinin Homepage
  license:
    name: MIT
    url: https://github.com/ghettovoice/vuelayers/blob/master/LICENSE
