# Used for CommonJS components build
#
# Format:
#   name - entry name
#   path - path relative to src
#
map:
  # common
  - name: ol
    path: ol

  - name: rx
    path: rx

  # mixins
  - name: mixins/rx-subs
    path: mixins/rx-subs

  - name: mixins/expose-inject
    path: mixins/expose-inject

  - name: mixins/geom
    path: mixins/geom

  # layer mixins
  - name: mixins/layer
    path: mixins/layer/layer

  - name: mixins/layer-tile
    path: mixins/layer/tile

  - name: mixins/layer-vector
    path: mixins/layer/vector

  # source mixins
  - name: mixins/source
    path: mixins/source/source

  - name: mixins/source-tile
    path: mixins/source/tile

  - name: mixins/source-xyz
    path: mixins/source/xyz

  - name: mixins/source-vector
    path: mixins/source/vector

  # style mixins
  - name: mixins/style
    path: mixins/style/style

  - name: mixins/style-image
    path: mixins/style/image

  # interaction mixins
  - name: mixins/interaction
    path: mixins/interaction/interaction

  # utils
  - name: utils/func
    path: utils/func

  - name: utils/debug
    path: utils/debug

  # components
  - name: map
    path: components/map

  - name: map-view
    path: components/map-view

  - name: geoloc
    path: components/geoloc

  - name: feature
    path: components/feature

  # geom components
  - name: geom-point
    path: components/geom/point

  - name: geom-line-string
    path: components/geom/line-string

  - name: geom-polygon
    path: components/geom/polygon

  - name: geom-multi-point
    path: components/geom/multi-point

  - name: geom-multi-line-string
    path: components/geom/multi-line-string

  - name: geom-multi-polygon
    path: components/geom/multi-polygon

  # layer components
  - name: layer-tile
    path: components/layer/tile

  - name: layer-vector
    path: components/layer/vector

  # source components
  - name: source-mapbox
    path: components/source/mapbox

  - name: source-osm
    path: components/source/osm

  - name: source-vector
    path: components/source/vector

  - name: source-xyz
    path: components/source/xyz

  # style components
  - name: style-container
    path: components/style-container

  - name: style-function
    path: components/style-function

  - name: style-fill
    path: components/style/fill

  - name: style-stroke
    path: components/style/stroke

  - name: style-circle
    path: components/style/circle

  - name: style-icon
    path: components/style/icon
