# Used for CommonJS components build
#
# Format:
#   name - entry name
#   path - path relative to src
#   alias - alias that used in source code
#
map:
####################################################################
#   OPENLAYERS EXTENSIONS
####################################################################
  - name: ol
    path: ol
    alias: vl-ol

  - name: ol/consts
    path: ol/consts
    alias: vl-ol/consts

  - name: ol/coordinate
    path: ol/coordinate
    alias: vl-ol/coordinate

  - name: ol/extent
    path: ol/extent
    alias: vl-ol/extent

  - name: ol/geojson
    path: ol/geojson
    alias: vl-ol/geojson

  - name: ol/style
    path: ol/style
    alias: vl-ol/style

####################################################################
#   RXJS EXTENSIONS
####################################################################
  - name: rx
    path: rx
    alias: vl-rx

  - name: rx/from-ol-event
    path: rx/from-ol-event
    alias: vl-rx/from-ol-event

#####################################################################
#   UTILS
#####################################################################
  - name: utils/coalesce
    path: utils/coalesce
    alias: vl-utils/coalesce

  - name: utils/debug
    path: utils/debug
    alias: vl-utils/debug

  - name: utils/is-numeric
    path: utils/is-numeric
    alias: vl-utils/is-numeric

  - name: utils/replace-tokens
    path: utils/replace-tokens
    alias: vl-utils/replace-tokens

  - name: utils/timed-chunk
    path: utils/timed-chunk
    alias: vl-utils/timed-chunk

  - name: utils/plain-props
    path: utils/plain-props
    alias: vl-utils/plain-props

#####################################################################
#   MIXINS
#####################################################################
  - name: mixins/rx-subs
    path: mixins/rx-subs
    alias: vl-mixins/rx-subs

  - name: mixins/stub-vnode
    path: mixins/stub-vnode
    alias: vl-mixins/stub-vnode

#####################################################################
#   COMMON COMPONENTS
#####################################################################
  - name: map
    path: components/map
    alias: vl-components/map

  - name: view
    path: components/view
    alias: vl-components/view

  - name: geoloc
    path: components/geoloc
    alias: vl-components/geoloc

  - name: feature
    path: components/feature
    alias: vl-components/feature

########################################################################
#   GEOM
########################################################################
  # mixins
  - name: mixins/geom
    path: components/geom/geom
    alias: vl-components/geom/geom

  # components
  - name: geom-point
    path: components/geom/point
    alias: vl-components/geom/point

  - name: geom-line-string
    path: components/geom/line-string
    alias: vl-components/geom/line-string

  - name: geom-polygon
    path: components/geom/polygon
    alias: vl-components/geom/polygon

  - name: geom-multi-point
    path: components/geom/multi-point
    alias: vl-components/geom/multi-point

  - name: geom-multi-line-string
    path: components/geom/multi-line-string
    alias: vl-components/geom/multi-line-string

  - name: geom-multi-polygon
    path: components/geom/multi-polygon
    alias: vl-components/geom/multi-polygon

##########################################################################
#   LAYER
##########################################################################
  # mixins
  - name: mixins/layer
    path: components/layer/layer
    alias: vl-components/layer/layer

  - name: mixins/layer-tile
    path: components/layer/tile-base
    alias: vl-components/layer/tile-base

  - name: mixins/layer-vector
    path: components/layer/vector-base
    alias: vl-components/layer/vector-base

  # components
  - name: layer-tile
    path: components/layer/tile
    alias: vl-components/layer/tile

  - name: layer-vector
    path: components/layer/vector
    alias: vl-components/layer/vector

##########################################################################
#   SOURCE
##########################################################################
  # mixins
  - name: mixins/source
    path: components/source/source
    alias: vl-components/source/source

  - name: mixins/source-vector
    path: components/source/vector-base
    alias: vl-components/source/vector-base

  - name: mixins/source-tile
    path: components/source/tile-base
    alias: vl-components/source/tile-base

  - name: mixins/source-xyz
    path: components/source/xyz-base
    alias: vl-components/source/xyz-base

  - name: mixins/source-wms
    path: components/source/wms-base
    alias: vl-components/source/wms-base

  # components
  - name: source-vector
    path: components/source/vector
    alias: vl-components/source/vector

  - name: source-xyz
    path: components/source/xyz
    alias: vl-components/source/xyz

  - name: source-mapbox
    path: components/source/mapbox
    alias: vl-components/source/mapbox

  - name: source-osm
    path: components/source/osm
    alias: vl-components/source/osm

  - name: source-wms
    path: components/source/wms
    alias: vl-components/source/wms

#############################################################################
#   STYLE
#############################################################################
  # mixins
  - name: mixins/style
    path: components/style/style
    alias: vl-components/style/style

  - name: mixins/style-image
    path: components/style/image
    alias: vl-components/style/image

  - name: mixins/style-target
    path: components/style/target
    alias: vl-components/style/target

  # components
  - name: style-func
    path: components/style/func
    alias: vl-components/style/func

  - name: style-container
    path: components/style/container
    alias: vl-components/style/container

  - name: style-fill
    path: components/style/fill
    alias: vl-components/style/fill

  - name: style-stroke
    path: components/style/stroke
    alias: vl-components/style/stroke

  - name: style-circle
    path: components/style/circle
    alias: vl-components/style/circle

  - name: style-icon
    path: components/style/icon
    alias: vl-components/style/icon

#############################################################################
#  INTERACTION
#############################################################################
  # mixins
  - name: mixins/interaction
    path: components/interaction/interaction
    alias: vl-components/interaction/interaction

  # components
  - name: interaction-select
    path: components/interaction/select
    alias: vl-components/interaction/select
