# Used for CommonJS components build
#
# Format:
#   name - entry name
#   path - path relative to src
#
map:
  # common
  - name: ol
    path: ol

  - name: rx
    path: rx
  # mixins
  - name: mixins/rx-subs
    path: mixins/rx-subs

  - name: mixins/expose-inject
    path: mixins/expose-inject

  - name: mixins/geom
    path: mixins/geom

  - name: mixins/layer
    path: mixins/layer/layer

  - name: mixins/layer-tile
    path: mixins/layer/tile

  - name: mixins/layer-vector
    path: mixins/layer/vector

  - name: mixins/source
    path: mixins/source/source

  - name: mixins/source-tile
    path: mixins/source/tile

  - name: mixins/source-xyz
    path: mixins/source/xyz

  - name: mixins/source-vector
    path: mixins/source/vector
  # utils
  - name: utils/func
    path: utils/func
  # components
  - name: map
    path: components/map

  - name: map-view
    path: components/map-view

  - name: geoloc
    path: components/geoloc

  - name: feature
    path: components/feature

  - name: geom-point
    path: components/geom/point

  - name: geom-line
    path: components/geom/line

  - name: geom-polygon
    path: components/geom/polygon

  - name: geom-multi-point
    path: components/geom/multi-point

  - name: geom-multi-line
    path: components/geom/multi-line

  - name: geom-multi-polygon
    path: components/geom/multi-polygon

  - name: layer-tile
    path: components/layer/tile

  - name: layer-vector
    path: components/layer/vector

  - name: source-mapbox
    path: components/source/mapbox

  - name: source-osm
    path: components/source/osm

  - name: source-vector
    path: components/source/vector

  - name: source-xyz
    path: components/source/xyz
